version: "3.0.1"
services:
  app:
    env_file:
      - .env
    image: mindspace-backend
    container_name: mindspace-backend
    ports:
      - "80:8080"
    networks:
      - mindspace-network
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    container_name: mindspace-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "mindspace"
    ports:
      - "5432:5432"
    networks:
      - mindspace-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  mindspace-network:
    driver: bridge

volumes:
  db-data:
    driver: local
